const $ = (s, p=document) => p.querySelector(s);
const $$ = (s, p=document) => [...p.querySelectorAll(s)];
const toast = (msg) => { const el=$('#toast'); el.textContent=msg; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove('show'),2400); };

const homeTemplate = () => `
  <section class="hero"><div class="hero-copy"><span class="eyebrow">AI가 연결하는 콘텐츠와 고객의 목소리</span><h1>콘텐츠의 문제는 더 빠르게 찾고,<br><strong>대응은 더 정확하게</strong></h1><p>광고, 홍보 영상, 유튜브, SNS 게시물에 접수된 의견을 콘텐츠 단위로 모아 핵심 쟁점과 위험도를 분석하는 AI 기반 콘텐츠 민원 관리 서비스입니다.</p><div class="hero-actions"><button class="primary" data-public="apply">콘텐츠 민원 접수 →</button><button class="secondary" data-public="track">처리 현황 조회</button></div></div><div class="hero-visual"><div class="ai-orb">AI</div><div class="float-card fc1"><span class="float-dot"></span> 콘텐츠 이슈 분석 완료<b>동일 쟁점 48건 통합</b></div><div class="float-card fc2">신규 증거 감지<b><span style="color:#246bfd">3건</span> 우선 확인</b></div></div></section>
  <div class="quick-strip"><button class="quick-item" data-public="apply"><span class="quick-icon">✎</span><span><b>콘텐츠 민원 접수</b><small>문제가 된 콘텐츠와 구간을 알려주세요</small></span></button><button class="quick-item" data-public="track"><span class="quick-icon">⌕</span><span><b>처리 현황 조회</b><small>접수번호로 진행 상황을 확인하세요</small></span></button><button class="quick-item" data-public="guide"><span class="quick-icon">?</span><span><b>이용 안내</b><small>콘텐츠ON 이용 방법을 안내합니다</small></span></button></div>
  <section class="section"><div class="section-heading"><span class="eyebrow">CONTENT CARE AI</span><h2>콘텐츠별로 연결되는 지능형 민원 관리</h2><p>반복 의견은 묶고, 새로운 증거와 위험 신호는 놓치지 않습니다.</p></div><div class="feature-grid"><article class="feature-card"><span class="feature-icon">AI</span><h3>AI 중립 정제</h3><p>욕설과 감정적 표현을 중립적인 업무 문장으로 바꾸고 핵심 요구사항, 긴급도, 난이도와 담당 부서를 분석합니다.</p></article><article class="feature-card"><span class="feature-icon">◎</span><h3>콘텐츠 이슈 군집화</h3><p>동일 콘텐츠의 같은 쟁점을 하나의 이슈로 통합하고 반복 의견과 새로운 증거를 구분합니다.</p></article><article class="feature-card"><span class="feature-icon">⚡</span><h3>사실·주장·검증 구분</h3><p>확인된 사실, 민원인의 주장, 추가 검증이 필요한 내용을 분리해 안전한 판단을 지원합니다.</p></article></div></section>
  <section class="section process"><div class="section-heading"><h2>콘텐츠 민원 처리 절차</h2><p>콘텐츠 연결부터 공식 안내까지 진행 상황을 투명하게 확인할 수 있습니다.</p></div><div class="steps"><div class="step"><span class="step-num">01</span><h4>콘텐츠 연결 접수</h4><p>URL과 문제 구간 등록</p></div><div class="step"><span class="step-num">02</span><h4>AI 정제·분석</h4><p>쟁점, 위험도, 담당 분류</p></div><div class="step"><span class="step-num">03</span><h4>이슈 통합 검토</h4><p>반복 의견과 신규 증거 구분</p></div><div class="step"><span class="step-num">04</span><h4>공식 답변</h4><p>담당자 검토 후 안내</p></div></div></section>`;

const applyTemplate = () => `<section class="page-shell"><div class="page-title"><span class="eyebrow">CONTENT COMPLAINT</span><h1>콘텐츠 민원 접수</h1><p>문제가 제기된 콘텐츠와 구간을 정확하게 입력해 주세요.</p></div><form class="form-card" id="complaintForm"><div class="form-grid"><label class="field">민원인 성명<input required placeholder="성명을 입력하세요"></label><label class="field">연락처<input required placeholder="010-0000-0000"></label><label class="field">대상 콘텐츠명<input required placeholder="예: 여름 캠페인 브랜드 필름"></label><label class="field">콘텐츠 유형<select><option>광고</option><option>홍보물·카드뉴스</option><option>홍보 영상</option><option>유튜브 콘텐츠</option><option>SNS 게시물</option><option>기타</option></select></label><label class="field full">콘텐츠 URL<input type="url" required placeholder="https:// 콘텐츠 주소를 입력하세요"></label><label class="field">게시 채널<input placeholder="예: 공식 유튜브, 인스타그램"></label><label class="field">문제 장면·영상 시간<input placeholder="예: 01:12~01:28 또는 카드뉴스 3페이지"></label><label class="field full">문제 유형<select><option>사실 오류·오해 가능성</option><option>차별·혐오 표현</option><option>저작권·초상권</option><option>선정성·폭력성</option><option>개인정보 노출</option><option>브랜드·제품 정보 오류</option><option>기타</option></select></label><label class="field full">민원 제목<input required placeholder="문제와 요청사항을 간략하게 작성해 주세요"></label><label class="field full">민원 내용<textarea required placeholder="문제가 된 표현, 확인이 필요한 사실, 수정 또는 삭제 요청 등을 구체적으로 작성해 주세요."></textarea></label><label class="field full">증빙 자료<input type="file" multiple></label></div><div class="form-actions"><button type="button" class="secondary" data-public="home">취소</button><button class="primary">콘텐츠 민원 접수</button></div></form></section>`;
const trackTemplate = () => `<section class="page-shell"><div class="page-title"><span class="eyebrow">TRACKING</span><h1>처리 현황 조회</h1><p>접수 시 발급된 콘텐츠 민원 접수번호를 입력해 주세요.</p></div><div class="lookup-card"><div class="lookup-row"><input id="trackNumber" value="C2026-0723-1842" placeholder="예: C2026-0000-0000"><button class="primary" id="trackButton">조회하기</button></div><div class="result-box" id="trackResult"><span class="badge green">검토 중</span><h3>브랜드 필름 내 친환경 인증 표현 확인 요청</h3><p style="color:#667085;font-size:13px">접수번호 C2026-0723-1842 · 공식 유튜브 · 브랜드커뮤니케이션팀</p><div class="timeline"><div class="done">접수 완료<small>07.23</small></div><div class="done">AI 정제·분석<small>07.23</small></div><div class="done">담당자 검토<small>진행 중</small></div><div>공식 답변<small>-</small></div></div></div></div></section>`;
const infoTemplate = (about=false) => `<section class="page-shell"><div class="page-title"><span class="eyebrow">${about?'ABOUT CONTENT ON':'USER GUIDE'}</span><h1>${about?'콘텐츠ON 서비스 소개':'이용 안내'}</h1><p>${about?'디지털 콘텐츠와 고객의 목소리를 AI로 안전하게 연결합니다.':'콘텐츠 URL과 문제 구간을 준비하면 더 빠르게 처리할 수 있습니다.'}</p></div><div class="info-card"><div class="feature-grid" style="grid-template-columns:repeat(3,1fr)"><article class="feature-card"><span class="feature-icon">1</span><h3>콘텐츠 지정</h3><p>콘텐츠명, 유형, URL, 게시 채널과 문제가 된 장면 또는 시간을 입력합니다.</p></article><article class="feature-card"><span class="feature-icon">2</span><h3>쟁점과 근거 작성</h3><p>확인한 사실과 의견, 검증이 필요한 의혹을 구분하고 증빙 자료를 첨부합니다.</p></article><article class="feature-card"><span class="feature-icon">3</span><h3>결과 확인</h3><p>접수번호로 AI 분석, 담당자 검토와 공식 답변 상태를 확인합니다.</p></article></div></div></section>`;

const publicTemplates={home:homeTemplate,apply:applyTemplate,track:trackTemplate,guide:()=>infoTemplate(false),about:()=>infoTemplate(true)};
function showPublic(page='home'){ $('#publicContent').innerHTML=publicTemplates[page](); window.scrollTo(0,0); bindPublicActions(); if(page==='track') $('#trackButton').onclick=()=>$('#trackResult').classList.add('show'); if(page==='apply') $('#complaintForm').onsubmit=e=>{e.preventDefault(); toast('콘텐츠 민원이 접수되었습니다. 접수번호 C2026-0723-1843'); showPublic('track'); setTimeout(()=>$('#trackResult').classList.add('show'),200);}; }
function bindPublicActions(){ $$('[data-public]').forEach(btn=>btn.onclick=e=>{e.preventDefault();showPublic(btn.dataset.public)}); }

const complaintRows = [
 ['C2026-1842','친환경 인증 표현 확인 요청','여름 캠페인 브랜드 필름','공식 유튜브','01:12~01:28','검토 중','high','48'],
 ['C2026-1841','카드뉴스 통계 출처 오류 제보','2026 소비 트렌드 카드뉴스','인스타그램','3페이지','신규','high','17'],
 ['C2026-1839','모델 이미지 사용 범위 문의','신제품 론칭 숏폼','틱톡','00:08','담당 배정','normal','6'],
 ['C2026-1836','이벤트 조건 표기 누락 신고','SUMMER WEEK 프로모션','공식 블로그','이벤트 배너','검토 중','normal','23'],
 ['C2026-1831','자막 내 제품명 오탈자 수정 요청','브랜드 인터뷰 EP.4','유튜브','04:31','답변 완료','normal','4']
];
const tableRows=()=>complaintRows.map(r=>`<tr data-detail="${r[0]}"><td>${r[6]==='high'?'<i class="risk-dot"></i>':''}${r[0]}</td><td><b>${r[2]}</b><br><small>${r[1]}</small></td><td>${r[3]}</td><td>${r[4]}</td><td><b>${r[7]}건</b></td><td><span class="badge ${r[5]==='답변 완료'?'green':r[5]==='신규'?'orange':''}">${r[5]}</span></td></tr>`).join('');
const adminHeader=(title,desc,action='')=>`<div class="admin-title"><div><h1>${title}</h1><p>${desc}</p></div>${action||'<button class="date-chip">2026. 07. 22 ▾</button>'}</div>`;
const dashboard=()=>`<div class="admin-content">${adminHeader('콘텐츠 민원 대시보드','접수 현황과 콘텐츠별 주요 쟁점을 한눈에 확인하세요.')}<div class="stat-grid"><div class="stat-card"><div class="stat-card-top">오늘 접수 <i>▤</i></div><h2>128</h2><span class="trend">↑ 12.5% 전일 대비</span></div><div class="stat-card"><div class="stat-card-top">검토 중 <i>◷</i></div><h2>86</h2><span class="trend orange">평균 1.8일 소요</span></div><div class="stat-card"><div class="stat-card-top">활성 콘텐츠 이슈 <i>◎</i></div><h2>14</h2><span class="trend">232건 통합 관리</span></div><div class="stat-card"><div class="stat-card-top">위험 민원 <i style="color:#e5484d;background:#ffedef">!</i></div><h2>3</h2><span class="trend orange">즉시 확인 필요</span></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><h3>주간 콘텐츠 민원 접수 추이</h3><button>상세 보기 →</button></div><div class="bar-chart">${[48,62,55,78,68,88,51].map((h,i)=>`<div class="bar" style="height:${h}%"><span>${['월','화','수','목','금','토','일'][i]}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>급상승 콘텐츠 이슈</h3><button data-admin="issues">전체 보기 →</button></div><div class="issue-list"><div class="issue"><span>01</span><div><b>친환경 인증 표현</b><small>여름 캠페인 브랜드 필름 · 48건</small></div><em>+132%</em></div><div class="issue"><span>02</span><div><b>통계 출처 오류</b><small>소비 트렌드 카드뉴스 · 31건</small></div><em>+74%</em></div><div class="issue"><span>03</span><div><b>이벤트 조건 누락</b><small>SUMMER WEEK 배너 · 23건</small></div><em>+48%</em></div><div class="issue"><span>04</span><div><b>모델 이미지 사용</b><small>신제품 론칭 숏폼 · 19건</small></div><em>+21%</em></div></div></section></div><section class="panel table-panel"><div class="panel-head"><h3>최근 콘텐츠 민원</h3><button data-admin="complaints">전체 보기 →</button></div><div class="table-wrap"><table><thead><tr><th>접수번호</th><th>대상 콘텐츠 / 민원</th><th>게시 채널</th><th>문제 구간</th><th>관련 민원</th><th>상태</th></tr></thead><tbody>${tableRows()}</tbody></table></div></section></div>`;
const complaints=()=>`<div class="admin-content">${adminHeader('콘텐츠 민원 관리','콘텐츠와 연결된 민원을 검색하고 처리 상태를 관리합니다.','<button class="primary">+ 민원 등록</button>')}<section class="panel"><div class="toolbar"><select><option>전체 상태</option><option>신규</option><option>검토 중</option><option>답변 완료</option></select><select><option>전체 유형</option><option>광고·홍보 영상</option><option>카드뉴스</option><option>SNS 게시물</option></select><input id="tableSearch" placeholder="⌕  콘텐츠명, URL, 채널, 접수번호 검색"></div><div class="table-wrap"><table><thead><tr><th>접수번호</th><th>대상 콘텐츠 / 민원</th><th>게시 채널</th><th>문제 구간</th><th>관련 민원</th><th>상태</th></tr></thead><tbody id="complaintBody">${tableRows()}</tbody></table></div></section></div>`;
const detail=()=>`<div class="admin-content">${adminHeader('콘텐츠 민원 상세','C2026-1842','<button class="secondary" data-admin="complaints">← 목록으로</button>')}<div class="detail-layout"><section class="panel"><div class="panel-head"><div><span class="badge orange">검토 중</span> <span class="badge red">긴급도 높음</span> <span class="badge">동일 콘텐츠 48건</span></div><small>접수 2026.07.23 09:32</small></div><h2 style="font-size:20px">브랜드 필름 내 친환경 인증 표현 확인 요청</h2><div class="detail-block"><h3>대상 콘텐츠</h3><p><b>여름 캠페인 브랜드 필름 〈BETTER TOMORROW〉</b><br>유형: 홍보 영상　·　채널: 공식 유튜브<br>문제 구간: 01:12~01:28　·　<a href="#" style="color:#246bfd">콘텐츠 URL 열기 ↗</a></p></div><div class="detail-block"><h3>민원 원문</h3><p>“영상에서 100% 친환경 인증을 받았다고 하는데 인증 번호도 없고 근거 링크도 없네요. 소비자를 속이는 거 아닌가요? 당장 내려주세요.”</p></div><div class="detail-block"><h3>AI 중립 정제문</h3><p>영상 01:12~01:28 구간의 ‘100% 친환경 인증’ 표현에 인증 번호와 근거 자료가 제시되지 않았다는 의견입니다. 해당 표현의 사실관계 확인과 근거 공개 또는 콘텐츠 수정을 요청합니다.</p></div><div class="detail-block"><h3>첨부 자료</h3><button class="secondary">📎 문제구간_캡처.png</button> <button class="secondary">📎 인증조회_결과.pdf</button></div><div class="detail-block"><h3>처리 이력</h3><p>09:32 접수　·　09:33 AI 정제 완료　·　09:34 기존 이슈에 통합　·　10:05 브랜드커뮤니케이션팀 배정</p></div></section><aside><section class="panel ai-box"><div class="panel-head"><h4>✦ AI 분석 결과</h4><span class="badge green">신뢰도 94%</span></div><h3>핵심 요구사항</h3><p>친환경 인증 표현의 근거 확인 및 공개, 사실과 다를 경우 해당 구간 수정 또는 게시 중단.</p><h3>사실성 구분</h3><p><span class="badge green">확인된 사실</span> 영상에 ‘100% 친환경 인증’ 문구 노출</p><p><span class="badge orange">민원인의 주장</span> 인증 근거가 공개되지 않았음</p><p><span class="badge red">검증 필요</span> 실제 인증 유효 여부와 표현 범위</p><h3>분류 및 담당</h3><span class="tag">사실 오류 가능성</span><span class="tag">그린워싱 의혹</span><span class="tag">브랜드커뮤니케이션팀</span><h3>긴급도 82% · 처리 난이도 높음</h3><div class="progress"><i style="width:82%"></i></div><p style="font-size:10px">대외 확산 증가 · 법무 및 ESG 부서 교차 검토 필요</p><h3>이슈 내 의견 구분</h3><p>반복 의견 44건 · 신규 증거 3건 · 구체 정보 1건</p></section><section class="panel" style="margin-top:15px"><h3>처리 담당</h3><p><b>브랜드커뮤니케이션팀 · 이지훈 매니저</b><br>협업: ESG경영팀, 법무팀<br>처리 기한 2026.07.25</p><button class="primary full" id="draftButton">공식 안내문 초안 생성</button></section></aside></div></div>`;
const issues=()=>`<div class="admin-content">${adminHeader('콘텐츠 이슈 클러스터','동일 콘텐츠에서 발생한 같은 쟁점을 AI가 하나의 이슈로 통합합니다.')}<div class="stat-grid">${[['친환경 인증 표현','48건','신규 증거 3'],['통계 출처 오류','31건','구체 정보 5'],['이벤트 조건 누락','23건','신규 증거 2'],['모델 이미지 사용','19건','반복 17']].map((x,i)=>`<div class="stat-card"><div class="stat-card-top">이슈 ${String(i+1).padStart(2,'0')} <i>◉</i></div><h3>${x[0]}</h3><b>${x[1]}</b> <span class="trend orange">${x[2]}</span><div class="progress" style="margin-top:14px"><i style="width:${90-i*15}%"></i></div></div>`).join('')}</div><section class="panel table-panel"><div class="panel-head"><h3>콘텐츠별 통합 이슈</h3><button>AI 군집 다시 분석 ↻</button></div><div class="issue-list"><div class="issue"><span>01</span><div><b>〈BETTER TOMORROW〉 친환경 인증 근거 쟁점</b><small>유튜브 · 48건 · 반복 44 / 신규 증거 3 / 구체 정보 1</small></div><span class="badge red">급상승</span></div><div class="issue"><span>02</span><div><b>〈2026 소비 트렌드〉 통계 출처 및 수치 오류</b><small>인스타그램 · 31건 · 반복 26 / 구체 정보 5</small></div><span class="badge orange">검증 중</span></div><div class="issue"><span>03</span><div><b>〈SUMMER WEEK〉 이벤트 참여 조건 누락</b><small>공식 블로그 · 23건 · 반복 20 / 신규 증거 2 / 기타 1</small></div><span class="badge">분석 중</span></div></div></section></div>`;
const risk=()=>`<div class="admin-content">${adminHeader('위험 콘텐츠 민원','법적·평판·개인정보 위험이 감지된 민원을 우선 확인하세요.')}<section class="panel" style="border-top:3px solid #e5484d"><div class="panel-head"><h3>즉시 확인 필요 <span class="badge red">3건</span></h3><small>AI는 의혹을 사실로 단정하지 않으며, 위험 신호는 담당자의 검증이 필요합니다.</small></div><div class="table-wrap"><table><thead><tr><th>위험도</th><th>대상 콘텐츠 / 문제 구간</th><th>감지 사유</th><th>확산</th><th>담당</th></tr></thead><tbody><tr><td><span class="badge red">매우 높음</span></td><td><b>임직원 인터뷰 비하인드</b><br><small>02:41 개인정보 노출</small></td><td>전화번호·주소 노출 가능성</td><td>관련 8건</td><td>개인정보보호팀</td></tr><tr data-detail="C2026-1842"><td><span class="badge red">높음</span></td><td><b>여름 캠페인 브랜드 필름</b><br><small>01:12~01:28</small></td><td>친환경 인증 표현 검증 필요</td><td>관련 48건</td><td>브랜드커뮤니케이션팀</td></tr><tr><td><span class="badge orange">높음</span></td><td><b>신제품 론칭 숏폼</b><br><small>00:08 모델 이미지</small></td><td>초상권 사용 범위 의혹</td><td>관련 19건</td><td>법무팀</td></tr></tbody></table></div></section></div>`;
const responses=()=>`<div class="admin-content">${adminHeader('답변 및 공식 안내','AI 초안을 검토·수정한 뒤 민원 답변 또는 공식 안내문으로 등록합니다.')}<div class="detail-layout"><section class="panel"><h3>답변 대기 이슈 <span class="badge orange">12건</span></h3><div class="issue-list" style="margin-top:20px">${complaintRows.slice(0,4).map((r,i)=>`<div class="issue"><span>${i+1}</span><div><b>${r[2]}</b><small>${r[1]} · ${r[7]}건 통합</small></div><button class="secondary draft-select">작성</button></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>✦ AI 공식 안내문 초안</h3><span class="badge green">생성 완료</span></div><textarea style="width:100%;height:300px;border:1px solid #d9e0ea;border-radius:8px;padding:12px;line-height:1.7">안녕하세요. 〈BETTER TOMORROW〉 브랜드 필름의 친환경 인증 표현과 관련해 보내주신 의견을 확인했습니다.

현재 영상 01:12~01:28 구간의 표현과 인증 자료를 브랜드커뮤니케이션팀, ESG경영팀 및 법무팀이 함께 검토하고 있습니다. 해당 표현의 적정성은 아직 확인 중이며, 검증이 완료되기 전까지 제기된 의혹을 사실로 단정하기 어렵다는 점을 안내드립니다.

검토 결과에 따라 근거 자료를 보완하거나 필요한 경우 콘텐츠를 수정하겠습니다. 구체적인 확인 결과와 조치 내용은 처리 기한 내 다시 안내드리겠습니다.</textarea><div class="form-actions"><button class="secondary">임시 저장</button><button class="primary" id="completeResponse">최종 안내 등록</button></div></section></div></div>`;
const settings=()=>`<div class="admin-content">${adminHeader('시스템 설정','콘텐츠 민원 분류와 AI 분석 기준을 설정합니다.')}<section class="panel"><div class="settings-grid">${[['♙','관리자 계정 관리','계정, 역할 및 콘텐츠 접근 권한'],['▦','담당 부서 관리','브랜드·법무·ESG·고객지원 라우팅'],['⚠','콘텐츠 위험 기준','법적·평판·개인정보 위험 임계값'],['◎','동일 콘텐츠 군집 기준','URL·구간·쟁점 기반 통합 범위'],['AI','AI 정제 및 분석','중립 정제, 사실성 구분, 난이도 분석'],['♢','확산 알림 설정','민원 급증과 신규 증거 감지 알림'],['≡','콘텐츠 채널 관리','유튜브·SNS·홈페이지 채널 연결'],['↻','관리자 활동 기록','안내문·배정·콘텐츠 조치 이력']].map(x=>`<div class="setting-item"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><button>설정 →</button></div>`).join('')}</div></section></div>`;
const adminTemplates={dashboard,complaints,issues,risk,responses,settings,detail};
function showAdmin(page='dashboard'){ $('#adminContent').innerHTML=adminTemplates[page](); $$('[data-admin]').forEach(b=>b.onclick=()=>showAdmin(b.dataset.admin)); $$('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.admin===page)); $$('[data-detail]').forEach(r=>r.onclick=()=>showAdmin('detail')); const search=$('#tableSearch'); if(search) search.oninput=()=>$$('#complaintBody tr').forEach(tr=>tr.hidden=!tr.textContent.toLowerCase().includes(search.value.toLowerCase())); const draft=$('#draftButton'); if(draft) draft.onclick=()=>showAdmin('responses'); const complete=$('#completeResponse'); if(complete) complete.onclick=()=>toast('최종 안내문이 등록되고 콘텐츠 민원 처리가 완료되었습니다.'); $$('.draft-select').forEach(b=>b.onclick=()=>toast('선택한 콘텐츠 이슈의 AI 안내문 초안을 불러왔습니다.')); window.scrollTo(0,0); }

$('#openLogin').onclick=()=>$('#loginDialog').showModal(); $('#closeLogin').onclick=()=>$('#loginDialog').close();
$('#loginForm').onsubmit=e=>{e.preventDefault();$('#loginDialog').close();$('#publicApp').classList.add('hidden');$('#adminApp').classList.remove('hidden');showAdmin();toast('콘텐츠 민원 관리자 콘솔에 로그인했습니다.');};
$('#logout').onclick=()=>{$('#adminApp').classList.add('hidden');$('#publicApp').classList.remove('hidden');showPublic('home');toast('로그아웃되었습니다.');};
$('.side-toggle').onclick=()=>$('.sidebar').classList.toggle('open');
showPublic('home');
