const $ = (s, p=document) => p.querySelector(s);
const $$ = (s, p=document) => [...p.querySelectorAll(s)];
const toast = (msg) => { const el=$('#toast'); el.textContent=msg; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove('show'),2400); };

const homeTemplate = () => `
  <section class="hero"><div class="hero-copy"><span class="eyebrow">AI가 돕는 새로운 민원 경험</span><h1>국민의 목소리는 더 선명하게,<br><strong>처리는 더 신속하게</strong></h1><p>복잡한 표현은 이해하기 쉽게 정리하고, 핵심 요구사항을 정확히 전달하는 AI 기반 민원 처리 서비스입니다.</p><div class="hero-actions"><button class="primary" data-public="apply">민원 접수하기 →</button><button class="secondary" data-public="track">처리 현황 조회</button></div></div><div class="hero-visual"><div class="ai-orb">AI</div><div class="float-card fc1"><span class="float-dot"></span> AI 민원 분석 완료<b>핵심 요구 3건 추출</b></div><div class="float-card fc2">처리 시간 단축<b><span style="color:#246bfd">42%</span> 더 빠르게</b></div></div></section>
  <div class="quick-strip"><button class="quick-item" data-public="apply"><span class="quick-icon">✎</span><span><b>민원 접수</b><small>간편하고 정확하게 접수하세요</small></span></button><button class="quick-item" data-public="track"><span class="quick-icon">⌕</span><span><b>처리 현황 조회</b><small>접수번호로 진행 상황을 확인하세요</small></span></button><button class="quick-item" data-public="guide"><span class="quick-icon">?</span><span><b>이용 안내</b><small>민원ON 이용 방법을 안내합니다</small></span></button></div>
  <section class="section"><div class="section-heading"><span class="eyebrow">SMART SERVICE</span><h2>AI로 더 나아진 민원 서비스</h2><p>민원인과 담당자 모두를 위한 지능형 처리 기능을 제공합니다.</p></div><div class="feature-grid"><article class="feature-card"><span class="feature-icon">AI</span><h3>AI 민원 정리</h3><p>감정적인 표현과 중복 내용을 정리해 사실관계와 핵심 요구사항을 명확하게 전달합니다.</p></article><article class="feature-card"><span class="feature-icon">◎</span><h3>유사 민원 통합 분석</h3><p>같은 지역과 주제의 민원을 묶어 반복되는 문제와 주요 이슈를 빠르게 파악합니다.</p></article><article class="feature-card"><span class="feature-icon">⚡</span><h3>신속한 위험 감지</h3><p>위험 징후와 긴급도를 분석하여 우선 확인이 필요한 민원을 담당자에게 알려줍니다.</p></article></div></section>
  <section class="section process"><div class="section-heading"><h2>민원 처리 절차</h2><p>접수부터 답변까지 진행 상황을 투명하게 확인할 수 있습니다.</p></div><div class="steps"><div class="step"><span class="step-num">01</span><h4>민원 접수</h4><p>내용과 관련 자료 등록</p></div><div class="step"><span class="step-num">02</span><h4>AI 분석</h4><p>핵심 내용 및 담당 분류</p></div><div class="step"><span class="step-num">03</span><h4>담당자 처리</h4><p>담당 부서 검토 및 처리</p></div><div class="step"><span class="step-num">04</span><h4>답변 완료</h4><p>처리 결과 확인</p></div></div></section>`;

const applyTemplate = () => `<section class="page-shell"><div class="page-title"><span class="eyebrow">COMPLAINT APPLICATION</span><h1>민원 접수</h1><p>정확한 처리를 위해 아래 내용을 작성해 주세요.</p></div><form class="form-card" id="complaintForm"><div class="form-grid"><label class="field">민원인 성명<input required placeholder="성명을 입력하세요"></label><label class="field">연락처<input required placeholder="010-0000-0000"></label><label class="field">민원 분야<select><option>교통·도로</option><option>환경·위생</option><option>복지·보건</option><option>시설·안전</option><option>기타</option></select></label><label class="field">발생 지역<input placeholder="지역 또는 주소를 입력하세요"></label><label class="field full">민원 제목<input required placeholder="민원 내용을 간략하게 작성해 주세요"></label><label class="field full">민원 내용<textarea required placeholder="발생 상황, 요청 사항 등을 구체적으로 작성해 주세요."></textarea></label><label class="field full">첨부 파일<input type="file" multiple></label></div><div class="form-actions"><button type="button" class="secondary" data-public="home">취소</button><button class="primary">민원 접수하기</button></div></form></section>`;
const trackTemplate = () => `<section class="page-shell"><div class="page-title"><span class="eyebrow">TRACKING</span><h1>처리 현황 조회</h1><p>접수 시 발급된 민원 접수번호를 입력해 주세요.</p></div><div class="lookup-card"><div class="lookup-row"><input id="trackNumber" value="M2026-0722-1842" placeholder="예: M2026-0000-0000"><button class="primary" id="trackButton">조회하기</button></div><div class="result-box" id="trackResult"><span class="badge green">처리 중</span><h3>횡단보도 신호 체계 개선 요청</h3><p style="color:#667085;font-size:13px">접수번호 M2026-0722-1842 · 교통정책과</p><div class="timeline"><div class="done">접수 완료<small>07.20</small></div><div class="done">AI 분석<small>07.20</small></div><div class="done">담당자 처리<small>진행 중</small></div><div>답변 완료<small>-</small></div></div></div></div></section>`;
const infoTemplate = (about=false) => `<section class="page-shell"><div class="page-title"><span class="eyebrow">${about?'ABOUT MINWON ON':'USER GUIDE'}</span><h1>${about?'민원ON 서비스 소개':'이용 안내'}</h1><p>${about?'AI와 사람이 함께 만드는 더 나은 민원 처리':'누구나 쉽고 편리하게 민원 서비스를 이용할 수 있습니다.'}</p></div><div class="info-card"><div class="feature-grid" style="grid-template-columns:repeat(3,1fr)"><article class="feature-card"><span class="feature-icon">1</span><h3>내용 작성</h3><p>사실관계와 요청 사항을 중심으로 민원 내용을 작성합니다.</p></article><article class="feature-card"><span class="feature-icon">2</span><h3>접수번호 보관</h3><p>접수 완료 후 발급되는 번호를 안전하게 보관합니다.</p></article><article class="feature-card"><span class="feature-icon">3</span><h3>결과 확인</h3><p>처리 현황 조회 메뉴에서 진행 상태와 답변을 확인합니다.</p></article></div></div></section>`;

const publicTemplates={home:homeTemplate,apply:applyTemplate,track:trackTemplate,guide:()=>infoTemplate(false),about:()=>infoTemplate(true)};
function showPublic(page='home'){ $('#publicContent').innerHTML=publicTemplates[page](); window.scrollTo(0,0); bindPublicActions(); if(page==='track') $('#trackButton').onclick=()=>$('#trackResult').classList.add('show'); if(page==='apply') $('#complaintForm').onsubmit=e=>{e.preventDefault(); toast('민원이 접수되었습니다. 접수번호 M2026-0722-1843'); showPublic('track'); setTimeout(()=>$('#trackResult').classList.add('show'),200);}; }
function bindPublicActions(){ $$('[data-public]').forEach(btn=>btn.onclick=e=>{e.preventDefault();showPublic(btn.dataset.public)}); }

const complaintRows = [
 ['M2026-1842','횡단보도 신호 체계 개선 요청','교통·도로','김○현','오늘 09:32','처리 중','high'],
 ['M2026-1841','밤샘 공사 소음 및 분진 신고','환경·위생','이○진','오늘 08:51','신규','high'],
 ['M2026-1839','노후 어린이 놀이시설 보수 요청','시설·안전','박○우','어제 17:42','담당 배정','normal'],
 ['M2026-1836','마을버스 배차 간격 개선 건의','교통·도로','최○수','어제 15:18','처리 중','normal'],
 ['M2026-1831','복지관 프로그램 확대 요청','복지·보건','정○희','07.20 14:02','답변 완료','normal']
];
const tableRows=()=>complaintRows.map(r=>`<tr data-detail="${r[0]}"><td>${r[6]==='high'?'<i class="risk-dot"></i>':''}${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><span class="badge ${r[5]==='답변 완료'?'green':r[5]==='신규'?'orange':''}">${r[5]}</span></td></tr>`).join('');
const adminHeader=(title,desc,action='')=>`<div class="admin-title"><div><h1>${title}</h1><p>${desc}</p></div>${action||'<button class="date-chip">2026. 07. 22 ▾</button>'}</div>`;
const dashboard=()=>`<div class="admin-content">${adminHeader('대시보드','민원 처리 현황과 주요 이슈를 한눈에 확인하세요.')}<div class="stat-grid"><div class="stat-card"><div class="stat-card-top">오늘 접수 <i>▤</i></div><h2>128</h2><span class="trend">↑ 12.5% 전일 대비</span></div><div class="stat-card"><div class="stat-card-top">처리 중 <i>◷</i></div><h2>86</h2><span class="trend orange">평균 2.4일 소요</span></div><div class="stat-card"><div class="stat-card-top">처리 완료 <i>✓</i></div><h2>312</h2><span class="trend">↑ 8.2% 이번 주</span></div><div class="stat-card"><div class="stat-card-top">위험 민원 <i style="color:#e5484d;background:#ffedef">!</i></div><h2>3</h2><span class="trend orange">즉시 확인 필요</span></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><h3>주간 민원 접수 추이</h3><button>상세 보기 →</button></div><div class="bar-chart">${[48,62,55,78,68,88,51].map((h,i)=>`<div class="bar" style="height:${h}%"><span>${['월','ȭ','수','목','금','토','일'][i]}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>급상승 이슈</h3><button data-admin="issues">전체 보기 →</button></div><div class="issue-list"><div class="issue"><span>01</span><div><b>도심 공사 소음</b><small>환경·위생 · 48건</small></div><em>+32%</em></div><div class="issue"><span>02</span><div><b>마을버스 배차</b><small>교통·도로 · 31건</small></div><em>+24%</em></div><div class="issue"><span>03</span><div><b>어린이공원 안전</b><small>시설·안전 · 24건</small></div><em>+18%</em></div><div class="issue"><span>04</span><div><b>불법 주정차</b><small>교통·도로 · 19건</small></div><em>+12%</em></div></div></section></div><section class="panel table-panel"><div class="panel-head"><h3>최근 접수 민원</h3><button data-admin="complaints">전체 보기 →</button></div><div class="table-wrap"><table><thead><tr><th>접수번호</th><th>민원 제목</th><th>분야</th><th>민원인</th><th>접수일</th><th>상태</th></tr></thead><tbody>${tableRows()}</tbody></table></div></section></div>`;
const complaints=()=>`<div class="admin-content">${adminHeader('민원 관리','접수된 민원을 검색하고 처리 상태를 관리합니다.','<button class="primary">+ 민원 등록</button>')}<section class="panel"><div class="toolbar"><select><option>전체 상태</option><option>신규</option><option>처리 중</option><option>답변 완료</option></select><select><option>전체 분야</option><option>교통·도로</option><option>환경·위생</option></select><input id="tableSearch" placeholder="⌕  제목, 접수번호, 민원인 검색"></div><div class="table-wrap"><table><thead><tr><th>접수번호</th><th>민원 제목</th><th>분야</th><th>민원인</th><th>접수일</th><th>상태</th></tr></thead><tbody id="complaintBody">${tableRows()}</tbody></table></div></section></div>`;
const detail=()=>`<div class="admin-content">${adminHeader('민원 상세','M2026-1842','<button class="secondary" data-admin="complaints">← 목록으로</button>')}<div class="detail-layout"><section class="panel"><div class="panel-head"><div><span class="badge orange">처리 중</span> <span class="badge red">긴급도 높음</span></div><small>접수 2026.07.22 09:32</small></div><h2 style="font-size:20px">횡단보도 신호 체계 개선 요청</h2><div class="detail-block"><h3>민원 원문</h3><p>매일 출퇴근 시간에 중앙로 사거리 횡단보도를 이용하고 있습니다. 보행 신호가 너무 짧아 노약자와 어린이들이 건너기 어렵고, 우회전 차량과 충돌할 위험도 큽니다. 현장 확인 후 신호 시간을 조정해 주세요.</p></div><div class="detail-block"><h3>첨부 자료</h3><button class="secondary">📎 현장사진_01.jpg</button></div><div class="detail-block"><h3>처리 이력</h3><p>09:32 민원 접수　·　09:33 AI 분석 완료　·　10:05 교통정책과 배정</p></div></section><aside><section class="panel ai-box"><div class="panel-head"><h4>✦ AI 분석 결과</h4><span class="badge green">신뢰도 94%</span></div><h3>핵심 요약</h3><p>중앙로 사거리의 짧은 보행 신호와 우회전 차량으로 인한 안전사고 위험을 제기하며 신호 시간 조정을 요청함.</p><h3>분류 및 감지</h3><span class="tag">교통·도로</span><span class="tag">보행 안전</span><span class="tag">신호 체계</span><h3>긴급도</h3><div class="progress"><i style="width:82%"></i></div><p style="font-size:10px">안전사고 가능성 언급 · 취약계층 관련</p></section><section class="panel" style="margin-top:15px"><h3>처리 담당</h3><p><b>교통정책과 · 이지훈 주무관</b><br>처리 기한 2026.07.29</p><button class="primary full" id="draftButton">AI 답변 초안 생성</button></section></aside></div></div>`;
const issues=()=>`<div class="admin-content">${adminHeader('이슈 클러스터','유사 민원을 AI가 자동으로 묶어 주요 이슈를 분석합니다.')}<div class="stat-grid">${[['도심 공사 소음','48건','+32%'],['마을버스 배차 간격','31건','+24%'],['어린이공원 안전','24건','+18%'],['불법 주정차','19건','+12%']].map((x,i)=>`<div class="stat-card"><div class="stat-card-top">이슈 ${String(i+1).padStart(2,'0')} <i>◉</i></div><h3>${x[0]}</h3><b>${x[1]}</b> <span class="trend orange">${x[2]}</span><div class="progress" style="margin-top:14px"><i style="width:${90-i*15}%"></i></div></div>`).join('')}</div><section class="panel table-panel"><div class="panel-head"><h3>이슈별 민원 군집</h3><button>AI 분석 새로고침 ↻</button></div><div class="issue-list"><div class="issue"><span>01</span><div><b>중앙동 재개발 공사 야간 소음</b><small>48건 · 최초 접수 07.14 · 관련 지역 3개</small></div><span class="badge red">급상승</span></div><div class="issue"><span>02</span><div><b>서부권 마을버스 배차 지연</b><small>31건 · 최초 접수 07.17 · 관련 노선 4개</small></div><span class="badge orange">관찰</span></div><div class="issue"><span>03</span><div><b>어린이 놀이시설 파손 및 노후화</b><small>24건 · 최초 접수 07.18 · 관련 시설 6개</small></div><span class="badge">분석 중</span></div></div></section></div>`;
const risk=()=>`<div class="admin-content">${adminHeader('위험 민원','안전 위협과 긴급 징후가 감지된 민원을 우선 확인하세요.')}<section class="panel" style="border-top:3px solid #e5484d"><div class="panel-head"><h3>즉시 확인 필요 <span class="badge red">3건</span></h3><small>AI 위험 감지는 참고 정보이며 담당자의 확인이 필요합니다.</small></div><div class="table-wrap"><table><thead><tr><th>위험도</th><th>민원 제목</th><th>감지 사유</th><th>접수 시각</th><th>담당</th></tr></thead><tbody><tr><td><span class="badge red">매우 높음</span></td><td><b>옹벽 균열 및 붕괴 위험 신고</b></td><td>인명 사고 가능성</td><td>오늘 10:12</td><td>안전관리과</td></tr><tr data-detail="M2026-1842"><td><span class="badge red">높음</span></td><td><b>횡단보도 신호 체계 개선 요청</b></td><td>교통사고 위험</td><td>오늘 09:32</td><td>교통정책과</td></tr><tr><td><span class="badge orange">높음</span></td><td><b>공원 내 파손 전선 노출</b></td><td>감전 위험</td><td>어제 18:22</td><td>공원녹지과</td></tr></tbody></table></div></section></div>`;
const responses=()=>`<div class="admin-content">${adminHeader('답변 및 처리','AI 초안을 검토하고 최종 답변을 등록합니다.')}<div class="detail-layout"><section class="panel"><h3>답변 대기 민원 <span class="badge orange">12건</span></h3><div class="issue-list" style="margin-top:20px">${complaintRows.slice(0,4).map((r,i)=>`<div class="issue"><span>${i+1}</span><div><b>${r[1]}</b><small>${r[0]} · ${r[2]}</small></div><button class="secondary draft-select">작성</button></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>✦ AI 답변 초안</h3><span class="badge green">생성 완료</span></div><textarea style="width:100%;height:220px;border:1px solid #d9e0ea;border-radius:8px;padding:12px;line-height:1.7">안녕하세요. 귀하께서 접수하신 민원에 대해 현장 확인을 진행하였습니다. 해당 사거리의 보행 신호 운영 현황과 교통량을 검토하여 신호 시간 조정 가능 여부를 확인하겠습니다. 검토 결과는 처리 기한 내에 안내드리겠습니다.</textarea><div class="form-actions"><button class="secondary">임시 저장</button><button class="primary" id="completeResponse">최종 답변 등록</button></div></section></div></div>`;
const settings=()=>`<div class="admin-content">${adminHeader('시스템 설정','관리 기준과 AI 분석 옵션을 설정합니다.')}<section class="panel"><div class="settings-grid">${[['♙','관리자 계정 관리','계정, 역할 및 접근 권한'],['▦','부서 및 담당자 관리','민원 분류별 담당 부서'],['⚠','위험 판단 기준','위험·긴급 키워드와 임계값'],['◎','유사 민원 군집 기준','클러스터 분석 범위'],['AI','AI 분석 설정','요약·분류 모델 및 신뢰도'],['♢','알림 설정','위험 민원과 처리 기한 알림'],['≡','시스템 로그','접속 및 변경 이력'],['↻','관리자 활동 기록','답변·배정·상태 변경 기록']].map(x=>`<div class="setting-item"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><button>설정 →</button></div>`).join('')}</div></section></div>`;
const adminTemplates={dashboard,complaints,issues,risk,responses,settings,detail};
function showAdmin(page='dashboard'){ $('#adminContent').innerHTML=adminTemplates[page](); $$('[data-admin]').forEach(b=>b.onclick=()=>showAdmin(b.dataset.admin)); $$('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.admin===page)); $$('[data-detail]').forEach(r=>r.onclick=()=>showAdmin('detail')); const search=$('#tableSearch'); if(search) search.oninput=()=>$$('#complaintBody tr').forEach(tr=>tr.hidden=!tr.textContent.toLowerCase().includes(search.value.toLowerCase())); const draft=$('#draftButton'); if(draft) draft.onclick=()=>showAdmin('responses'); const complete=$('#completeResponse'); if(complete) complete.onclick=()=>toast('최종 답변이 등록되고 처리가 완료되었습니다.'); $$('.draft-select').forEach(b=>b.onclick=()=>toast('선택한 민원의 AI 답변 초안을 불러왔습니다.')); window.scrollTo(0,0); }

$('#openLogin').onclick=()=>$('#loginDialog').showModal(); $('#closeLogin').onclick=()=>$('#loginDialog').close();
$('#loginForm').onsubmit=e=>{e.preventDefault();$('#loginDialog').close();$('#publicApp').classList.add('hidden');$('#adminApp').classList.remove('hidden');showAdmin();toast('관리자 콘솔에 로그인했습니다.');};
$('#logout').onclick=()=>{$('#adminApp').classList.add('hidden');$('#publicApp').classList.remove('hidden');showPublic('home');toast('로그아웃되었습니다.');};
$('.side-toggle').onclick=()=>$('.sidebar').classList.toggle('open');
showPublic('home');
